# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

cache: packages

warnings_are_errors: false # TODO: set to false while testing

after_success:
  - Rscript -e 'covr::codecov()'

os:
  - linux

r:
  - oldrel
  - release

notifications:
  email:
    - paul.james379@gmail.com
